win_2012_std_scripts = ['\n',
                        '[Startup]\n',
                        '0CmdLine=C:\Windows\Setup\Scripts\SetupComplete.cmd\n',
                        '0Parameters=\n',
                        '1CmdLine=C:\Windows\Setup\Scripts\window2012std_init_script.bat\n',
                        '1Parameters=\n',
                        '2CmdLine=C:\Windows\Setup\Scripts\WindowsUserdataExecutor_powershell.bat\n',
                        '2Parameters=\n']
                        
win_2012_r2_std_scripts = ['\n',
                        '[Startup]\n',
                        '0CmdLine=C:\Windows\Setup\Scripts\SetupComplete.cmd\n',
                        '0Parameters=\n',
                        '1CmdLine=C:\Windows\Setup\Scripts\window2012r2std_init_script.bat\n',
                        '1Parameters=\n',
                        '2CmdLine=C:\Windows\Setup\Scripts\WindowsUserdataExecutor_powershell.bat\n',
                        '2Parameters=\n']

win_2016_std_scripts = ['\n',
                        '[Startup]\n',
                        '0CmdLine=C:\Windows\Setup\Scripts\SetupComplete.cmd\n',
                        '0Parameters=\n',
                        '1CmdLine=C:\Windows\Setup\Scripts\window2016std_init_script.bat\n',
                        '1Parameters=\n',
                        '2CmdLine=C:\Windows\Setup\Scripts\WindowsUserdataExecutor_powershell.bat\n',
                        '2Parameters=\n']

win_2019_std_scripts = ['\n',
                        '[Startup]\n',
                        '0CmdLine=C:\Windows\Setup\Scripts\SetupComplete.cmd\n',
                        '0Parameters=\n',
                        '1CmdLine=C:\Windows\Setup\Scripts\window2019std_init_script.bat\n',
                        '1Parameters=\n',
                        '2CmdLine=C:\Windows\Setup\Scripts\WindowsUserdataExecutor_powershell.bat\n',
                        '2Parameters=\n']

############################################################################################################
win_2012_std_scripts_mssql =['\n',
                            '[Startup]\n',
                            '0CmdLine=C:\Windows\Setup\Scripts\SetupComplete.cmd\n',
                            '0Parameters=\n',
                            '1CmdLine=C:\Windows\Setup\Scripts\window2012std_init_script.bat\n',
                            '1Parameters=\n',
                            '2CmdLine=C:\Windows\System32\GroupPolicy\Machine\Scripts\Startup\ktconf.bat\n',
                            '2Parameters=\n',
                            '3CmdLine=C:\Windows\Setup\Scripts\WindowsUserdataExecutor_powershell.bat\n',
                            '3Parameters=\n']
win_2012_r2_std_scripts_mssql =['\n',
                            '[Startup]\n',
                            '0CmdLine=C:\Windows\Setup\Scripts\SetupComplete.cmd\n',
                            '0Parameters=\n',
                            '1CmdLine=C:\Windows\Setup\Scripts\window2012r2std_init_script.bat\n',
                            '1Parameters=\n',
                            '2CmdLine=C:\Windows\System32\GroupPolicy\Machine\Scripts\Startup\ktconf.bat\n',
                            '2Parameters=\n',
                            '3CmdLine=C:\Windows\Setup\Scripts\WindowsUserdataExecutor_powershell.bat\n',
                            '3Parameters=\n']
win_2016_std_scripts_mssql =['\n',
                            '[Startup]\n',
                            '0CmdLine=C:\Windows\Setup\Scripts\SetupComplete.cmd\n',
                            '0Parameters=\n',
                            '1CmdLine=C:\Windows\Setup\Scripts\window2016std_init_script.bat\n',
                            '1Parameters=\n',
                            '2CmdLine=C:\Windows\System32\GroupPolicy\Machine\Scripts\Startup\ktconf.bat\n',
                            '2Parameters=\n',
                            '3CmdLine=C:\Windows\Setup\Scripts\WindowsUserdataExecutor_powershell.bat\n',
                            '3Parameters=\n']
win_2019_std_scripts_mssql =['\n',
                            '[Startup]\n',
                            '0CmdLine=C:\Windows\Setup\Scripts\SetupComplete.cmd\n',
                            '0Parameters=\n',
                            '1CmdLine=C:\Windows\Setup\Scripts\window2019std_init_script.bat\n',
                            '1Parameters=\n',
                            '2CmdLine=C:\Windows\System32\GroupPolicy\Machine\Scripts\Startup\ktconf.bat\n',
                            '2Parameters=\n',
                            '3CmdLine=C:\Windows\Setup\Scripts\WindowsUserdataExecutor_powershell.bat\n',
                            '3Parameters=\n']